# Generated by Django 5.0.6 on 2025-06-25 18:15

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_medium',
            field=models.ImageField(blank=True, null=True, upload_to='products/medium/',
                                    verbose_name='Среднее изображение'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_small',
            field=models.ImageField(blank=True, null=True, upload_to='products/small/',
                                    verbose_name='Маленькое изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='WEBP',
                                                         keep_meta=True, null=True, quality=85, scale=None,
                                                         size=[1200, 800], upload_to='products/',
                                                         verbose_name='Изображение'),
        ),
    ]
