# Generated by Django 5.0.6 on 2025-07-20 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0002_product_image_medium_product_image_small_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Изображение'),
        ),
    ]
