# Generated by Django 5.0.6 on 2025-07-20 14:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0003_category_description_category_image'),
    ]

    operations = [
    ]
