# Generated by Django 5.0.6 on 2025-07-20 14:40

from django.db import migrations


def forwards(apps, schema_editor):
    Category = apps.get_model('core', 'Category')
    for cat in Category.objects.all():
        try:
            cat.save()  # Это перегенерирует slug при необходимости
        except ValueError:
            # Обработка дубликатов
            cat.slug = f"{slugify(cat.name)}-{cat.id}"
            cat.save()


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0004_fix_duplicate_slugs'),
    ]

    operations = [
    ]
