# Generated by Django 5.0.6 on 2025-07-02 16:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0002_product_image_medium_product_image_small_and_more'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзины'},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'Элемент корзины', 'verbose_name_plural': 'Элементы корзины'},
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product')},
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('entrance', models.CharField(blank=True, max_length=10, verbose_name='Подъезд')),
                ('floor', models.CharField(blank=True, max_length=10, verbose_name='Этаж')),
                ('apartment', models.CharField(blank=True, max_length=10, verbose_name='Квартира')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('status', models.CharField(
                    choices=[('new', 'Новый'), ('confirmed', 'Подтвержден'), ('preparing', 'Готовится'),
                             ('delivering', 'В пути'), ('completed', 'Завершен'), ('cancelled', 'Отменен')],
                    default='new', max_length=20, verbose_name='Статус')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Оплачено')),
                ('delivery_cost',
                 models.DecimalField(decimal_places=2, default=150, max_digits=8, verbose_name='Стоимость доставки')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Итоговая стоимость')),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order',
                                              to='orders.cart')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                           to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
    ]
